<?php

    $action = $this->getAction();

?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?php echo (isset($this->page_title) ? $this->page_title : 'Welcome to my site'); ?></title>
    <!-- Links to scripts and stylesheets -->
    <link rel="stylesheet" href="/css/style.css" media="all">
    <script src="https://kit.fontawesome.com/4469be274f.js" crossorigin="anonymous"></script>
</head>

<body>
    <header>
        <div class="logo">
            <img src="/images/logo.jpeg" alt="logo Wendy Van Craen">
        </div>

        <div id="hamburger" class="hamburger">
                <div class="nav-line"></div>
                <div class="nav-line"></div>
                <div class="nav-line"></div>
            </div>

        <nav id="main-nav" class='main-nav'>
            <ul class="main-nav-links">
                <li><a href="/portfolio/index"
                        <?php echo ($action == 'portfolio/index' ? 'class=active' : ''); ?>>Portfolio</a></li>
                <li><a href="/home/aboutme" <?php echo ($action == 'home/aboutme' ? 'class=active' : ''); ?>>About me</a></li>
                <li><a href="/home/contact" <?php echo ($action == 'home/contact' ? 'class=active' : ''); ?>>Contact</a>
                </li>
            </ul>
        </nav>
    </header>