<?php include VIEW . 'header.phtml'; ?>

<div class="container">
    <section class="intro light-bg">
        <h1 class="anim-typewriter">
            Hello!
            <strong>I'm Wendy</strong>. <br>
            I'm a junior web developer and a graphic designer
        </h1><span class="line">|</span>
    </section> <!-- end of intro -->

    <section class="projects dark-bg">
    <h2>my <strong>Portfolio</strong></h2>
        
        <section class="project-article-wrapper">
        <?php if(array_key_exists('portfolio', $this->view_data)) : ?>
            <?php foreach($this->view_data['portfolio'] as $project) : ?>

            <article class="project-article">
                <div class="project-img-title">
                    <h3><?= $project->title; ?></h3>

                    <a href="<?= $project->url; ?>" target="_blank" rel="noreferrer"><img
                            src="../<?= $project->image; ?>" alt="image"></a>
                </div>
                <div class="project-info">
                    <p>
                        <strong>Skills: </strong>
                        <span>
                            <?= $project->skills?>
                        </span>
                    </p>
                    <p>
                        <strong>Description: </strong>
                        <span>
                            <?= $project->description?>
                        </span>
                    </p>
                </div>
                <div class="project-btns">
                    <button class="project-website"><a href="<?= $project->url?>" target="_blank"
                            rel="noreferrer">Project >></a></button>
                    <button class="project github"><a href="<?= $project->github?>" target="_blank"
                            rel="noreferrer">GitHub >></a></button>
                </div>


            </article> <!-- end of article -->
            <?php endforeach; ?>
        </section>
        <?php endif; ?>
    </section> <!-- end of projects -->

    <section class="dev-skills light-bg">
        <h2>Development <strong>Skills</strong></h2>
        <ul class="dev-skills-wrapper">
            <li class="dev-img"><img src="../images/html5.svg" alt="HTML 5"></li>
            <li class="dev-img"><img src="../images/css3.svg" alt="CSS 3"></li>
            <li class="dev-img"><img src="../images/javascript.svg" alt="Javascript">Javascript</li>
            <li class="dev-img"><img src="../images/sass.svg" alt="Sass"></li>
            <li class="dev-img"><img src="../images/json.svg" alt="JSON">JSON</li>
            <li class="dev-img"><img src="../images/ajax.svg" alt="JSON"></li>
            <li class="dev-img dev-img-big"><img src="../images/jquery.svg" alt="jQuery"></li>
            <li class="dev-img"><img src="../images/react.svg" alt="React.js">React.js <br>in progres...</li>
            <li class="dev-img"><img src="../images/php.svg" alt="PHP"></li>
            <li class="dev-img"><img src="../images/curl-logo.svg" alt="cURL"></li>
            <li class="dev-img"><img src="../images/mysql.svg" alt="MySQL"></li>
            <li class="dev-img"><img src="../images/wordpress-icon.svg" alt="Wordpress">wordpress</li>
            <li class="dev-img"><img src="../images/terminal.svg" alt="Command line">command line</li>
            <li class="dev-img dev-img-big"><img src="../images/git-icon.svg" alt="Git"></li>
</ul>
    </section> <!-- end of dev-skills -->
</div>

<?php include VIEW . 'footer.phtml'; ?>