<?php include VIEW . 'header.phtml'; ?>

<div class="container">
    <section class="intro">
        <h1>
            Hello!
            <strong>I'm Wendy</strong>. <br>
            I'm a junior web developer and a graphic designer
        </h1>
    </section>

    <?php if(array_key_exists('portfolio', $this->view_data)) : ?>

    <section class="projects dark-bg">
        <h2>my <strong>Portfolio</strong></h2>
        <section class="project-article-wrapper">
                    <?php foreach($this->view_data['portfolio'] as $project) : ?>

        <article class="project-article">
            <div class="project-img-title">
                <h3><?= $project->title; ?></h3>

                <a href="<?= $project->url; ?>" target="_blank" rel="noreferrer"><img src="../<?= $project->image; ?>"
                        alt="image"></a>
            </div>
            <div class="project-info">
                <p>
                    <strong>Skills: </strong>
                    <span>
                        <?= $project->skills?>
                    </span>
                </p>
                <p>
                    <strong>Description: </strong>
                    <span>
                        <?= $project->description?>
                    </span>
                </p>
            </div>
            <div class="project-btns">
                <button class="project-website"><a href="<?= $project->url?>" target="_blank" rel="noreferrer">Project >></a></button>
                <button class="project github"><a href="<?= $project->github?>" target="_blank"
                        rel="noreferrer">GitHub >></a></button>
            </div>


        </article> <!-- end of article -->
        <?php endforeach; ?>
        </section>


    </section> <!-- end of projects -->

    <?php endif; ?>
</div>

<?php include VIEW . 'footer.phtml'; ?>